version: 2
jobs:
    build:
        docker:
            - image: node
        steps:
            - checkout
            - run: npm install
            - run: npm run validate
            - run: npm run build
            - store_artifacts:
                path: rulebook.html
                destination: rulebook.html
