version: 2
jobs:
    build:
        docker:
            - image: node
        steps:
            - checkout
            - run: npm install -g inliner
            - run: 'inliner rules.html > rulebook.html'
            - store_artifacts:
                path: rulebook.html
                destination: rulebook.html
